### PR TITLE
use f-strings for string formatting (fixes #204)

### LINKED ISSUE #204: Replace uses of .format() with f-strings
If you run the following from the root of this repo.

```shell
pip install --upgrade pylint
pylint doppel/ | grep consider-using-f-string
```

You'll see the following warnings.

```text
doppel/describe.py:68:16: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/describe.py:71:14: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/describe.py:78:22: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/describe.py:81:14: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/describe.py:97:16: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/describe.py:103:14: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/DoppelTestError.py:17:15: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/PackageAPI.py:47:18: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/reporters.py:104:25: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/reporters.py:107:29: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/reporters.py:136:27: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/reporters.py:184:28: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/reporters.py:292:27: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/reporters.py:340:28: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
doppel/reporters.py:407:31: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
```

These should be converted to use f-strings. So for example.

```python
# before
"Could not figure out what {} is".format(obj_name)

# after
f"Could not figure out what {obj_name} is"
```

I'd welcome a pull request that converts these cases to f-strings.

## How this improves `doppel-cli`

See https://cito.github.io/blog/f-strings/ and other information linked in https://github.com/microsoft/LightGBM/issues/4136. In addition to being a bit easier to read for common cases, f-strings are actually faster than most other string interpolation options.

### PR DESCRIPTION
**Pull request by franklinen**
Fixes #204.

This small PR was made to change `{ }.format(a)` to f-strings, `f"( {a} )"`.

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks very much for this!

To fix the errors reported in https://github.com/jameslamb/doppel-cli/pull/205/checks?check_run_id=3783471821, please run the following from the root of the repo.

```shell
pip install --upgrade black
black .
```

**Comment by franklinen** [comment]
Hi James,
I hope you are doing good. I have applied the required code to the root of
the repo.

Let me know if it worked out.
*Frankline Ononiwu*

**Review by jameslamb — COMMENTED** [review]
Thanks for the updates! Changes look ok to me, let's see what the CI jobs say.

Please look at the changes I made to the description and title. Since this pull request is intended to fix an existing issue, it's important to link to that issue so that:

1. that issue will be automatically closed by merging the pull request
2. it is easier for me, as a reviewer, to understand _why_ you want to make these changes

**Review by jameslamb — APPROVED** [review]
Thanks for the help! I just pushed a new commit to this branch, fixing the formatting errors in https://github.com/jameslamb/doppel-cli/runs/4087165193?check_suite_focus=true.

I misinformed you in https://github.com/jameslamb/doppel-cli/pull/205#pullrequestreview-769610781, sorry! Should have been `black --line-length=100 .`.

I'll merge this once it builds. Since you chose to make this pull request from the `main` branch on your fork, and since this project uses squash-merging, once I merge this the `main` branch of your fork will not match the `main` branch of this project.

Once I merge this, if you'd like to make more contributions I recommend deleting your fork and creating those other contributions from branches that are not `main`.

Thanks again for the help!

**Comment by franklinen** [comment]
THanks James  for the experience  and help.  I don't  mind doing more contributions.  I think I'll do better with this  experience.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
